"""empty message

Revision ID: f03b2c649b76
Revises: 6cc8d5acaf9e
Create Date: 2018-02-28 11:52:21.345339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03b2c649b76'
down_revision = '6cc8d5acaf9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_type', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_type', 'description')
    # ### end Alembic commands ###
